version: 2.0

services:
    r2ui:
        image: serverking/r2ui
        ports:
            - "8000:80"
        links:
            - registry:registryalias
        restart: always
    
    registry:
        image: registry:2.3
        volumes:
            - ./registry:/var/lib/registry
        ports:
            - "5000:5000"
        restart: always

